### ISSUE TITLE
Team 3 - Sprint 4 - Feature Task - New Setting Page

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2021-ext-studio-2#413]
# Description
This feature is dedicated to changing the style of the setting button and background to make it more in line with our game content and background story. Use unique UI design to make these buttons attractive to players. 

# SubFeature/component
- Setting Button Image
- Setting Background

# Examples
- The backgorund in setting will fit to the menu background.
- The style of the button will be consistent and in line with each scene

# Dependencies
- Main menu backgroun (#160 )
- Emotion goals
- Game story

# **Tasks**
Detailed task description.
- Task 1: Design the style of background related to the game story and emotion goals.
- Task 2: Design the style of button related to the game story and emotion goals.
- Task 3: Add and merge the name and button into the game.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Task 1 (Oct. 13)
- [x] Task 2 (Oct. 14)
- [ ] Task 3 (Oct. 17) 

**Test and evaluation deadline (Oct. 18)**

# Members
- Zhenyu Ding (@7ayuu )

**Comment by Butcanudothis** [comment]
Hi @7ayuu , We already have a feature for redesigning settings screen #366, which has been allotted to us (team 7) as per this
[https://docs.google.com/document/d/1C6wncrRjtX32Qa6NilZSSmg7APl1jQTR4p8GAn3AAMM](https://docs.google.com/document/d/1C6wncrRjtX32Qa6NilZSSmg7APl1jQTR4p8GAn3AAMM) and our feature ticket has been approved by the tutor @uqtnieva 
Please close this feature ticket since this is a duplicate.
